{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "netbird-proxy.fullname" . }}
  labels:
    {{- include "netbird-proxy.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "netbird-proxy.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - port: https
          protocol: TCP
        {{- if .Values.acme.enabled }}
        - port: acme-http
          protocol: TCP
        {{- end }}
        - port: health
          protocol: TCP
        {{- if .Values.debug.enabled }}
        - port: debug
          protocol: TCP
        {{- end }}
        {{- if .Values.wireguard.enabled }}
        - port: wireguard
          protocol: UDP
        {{- end }}
    {{- with .Values.networkPolicy.additionalIngress }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
