{{- if and .Values.rbac.create .Values.serviceAccount.create (eq .Values.acme.certLockMethod "k8s-lease") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "netbird-proxy.fullname" . }}
  labels:
    {{- include "netbird-proxy.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "netbird-proxy.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "netbird-proxy.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
