{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird-proxy.fullname" . }}
  labels:
    {{- include "netbird-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.proxyToken | b64enc | quote }}
{{- end }}
---
{{- if and .Values.oidc.clientSecret (not .Values.oidc.existingOidcSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "netbird-proxy.oidcSecretName" . }}
  labels:
    {{- include "netbird-proxy.labels" . | nindent 4 }}
type: Opaque
data:
  oidc-client-secret: {{ .Values.oidc.clientSecret | b64enc | quote }}
{{- end }}
