fullnameOverride: "netbird-api-gateway"

controller:
  replicaCount: 1
  allowSnippetAnnotations: true
  nodeSelector:
    kubernetes.io/os: null
  service:
    type: ClusterIP
  admissionWebhooks:
    enabled: false
  ingressClassResource:
    name: netbird-api-gateway
    controllerValue: k8s.io/netbird-api-gateway
  ingressClass: netbird-api-gateway
  config:
    ssl-redirect: "true"
